- name: Upgrade all packages 
  package:
    name: "*"
    state: latest
- name: Reboot machine
  ansible.builtin.reboot:
- name: Install tooling (e.g. vim, htop, zsh)
  package:
    name:
      - sqlite
      - vim
      - htop
      - zsh
      - git
      - tmux
    state: latest
- name: Set zsh as default shell
  user:
    name: gdarruda
    shell: /bin/zsh
- name: Clean Oh My Zsh
  file:
    path: ~/.oh-my-zsh
    state: absent
  become_user: gdarruda
- name: Install Oh My Zsh
  shell: wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O - | sh
  become_user: gdarruda
- name: Configure Oh My Zsh
  copy:
     src: resources/.zshrc
     dest: ~/.zshrc
  become_user: gdarruda
- name: Settting git e-mail address
  shell: git config --global user.email "gabriel@gdarruda.me"
  become_user: gdarruda
- name: Settting git user name
  shell: git config --global user.name "Gabriel Arruda"
  become_user: gdarruda
- name: Install python dependencies
  package:
    name:
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - libuuid-devel
      - gdbm-devel
      - libnsl2-devel
- name: Install Pyenv
  shell: curl https://pyenv.run | bash
  become_user: gdarruda
- name: Setting pyenv on zsh
  shell: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    echo 'eval "$(pyenv init -)"' >> ~/.zshrc
  become_user: gdarruda
- name: Add RPM Fusion (free)
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ version }}.noarch.rpm
    disable_gpg_check: true
- name: Add RPM Fusion (non-free)
  dnf:
    name:
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ version }}.noarch.rpm
    disable_gpg_check: true
- name: Check Update DNF
  shell: dnf check-update
- name: Install Nvdia drivers
  dnf:
    name: 
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
    state: latest
- name: Reboot machine (Nvidia Drivers)
  ansible.builtin.reboot: