# - name: Upload config Keychron
#   copy:
#      src: resources/hid_apple.conf
#      dest: /etc/modprobe.d/hid_apple.conf
# - name: Set config Keychron
#   shell: dracut --regenerate-all --force
# - name: Reboot machine (Keychron)
#   ansible.builtin.reboot:
- name: Add RPM Fusion (free)
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ version }}.noarch.rpm
    disable_gpg_check: true
- name: Add RPM Fusion (non-free)
  dnf:
    name:
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ version }}.noarch.rpm
    disable_gpg_check: true
- name: Check Update DNF
  shell: dnf check-update
- name: Install Nvdia drivers
  dnf:
    name: 
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
    state: latest
- name: Reboot machine (Nvidia Drivers)
  ansible.builtin.reboot:
- name: Check if acpi_enforce_resources=lax is configured in the boot command
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=".*acpi_enforce_resources=lax'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false
- name: Add acpi_enforce_resources=lax to boot
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
    line: '\1 acpi_enforce_resources=lax"'
  when: grub_cmdline_check.found == 0
- name: Update grub
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
- name: Reboot machine (GRUB)
  ansible.builtin.reboot:
- name: Install sensors
  dnf:
    name: 
      - thinkfan 
      - lm_sensors
- name: Sensors detect
  shell: yes | sensors-detect
- name: Upload config thinkfan
  copy:
     src: resources/thinkfan.conf
     dest: /etc/thinkfan.conf
- name: Enable/Start thinkfan service
  systemd: 
    name: thinkfan
    state: started
    enabled: yes 