- name: Install alacritty
  dnf:
    name:
      - alacritty
- name: Copying alacritty.yml
  copy:
     src: resources/.alacritty.yml
     dest: ~/.alacritty.yml
  become_user: gdarruda
- name: Copying Xresources
  copy:
     src: resources/.Xresources
     dest: ~/.Xresources
  become_user: gdarruda
- name: Inverting mouse scroll
  copy:
     src: resources/40-libinput.conf
     dest: /usr/share/X11/xorg.conf.d/40-libinput.conf
- name: Copy i3 config
  copy:
    src: resources/config
    dest: ~/.config/i3/config
  become_user: gdarruda
- name: Create i3 config dir (status)
  file:
    path: ~/.config/i3status/
    state: directory
  become_user: gdarruda
- name: Copy i3 config (status)
  copy:
    src: resources/config_i3_status
    dest: ~/.config/i3status/config
  become_user: gdarruda
- name: Reboot machine (i3)
  ansible.builtin.reboot: