- name: Upgrade all packages 
  package:
    name: "*"
    state: latest
- name: Install tooling (e.g. vim, htop, zsh)
  package:
    name:
      - vim
      - htop
      - zsh
      - git
      - tmux
    state: latest
- name: Set zsh as default shell
  user:
    name: gdarruda
    shell: /bin/zsh
- name: Clean Oh My Zsh
  file:
    path: ~/.oh-my-zsh
    state: absent
  become_user: gdarruda
- name: Install Oh My Zsh
  shell: wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O - | sh
  become_user: gdarruda
- name: Configure Oh My Zsh
  copy:
     src: resources/.zshrc
     dest: ~/.zshrc
  become_user: gdarruda
- name: Settting git e-mail address
  shell: git config --global user.email "gabriel@gdarruda.me"
  become_user: gdarruda
- name: Settting git user name
  shell: git config --global user.name "Gabriel Arruda"
  become_user: gdarruda
- name: Install python dependencies
  package:
    name:
      - python3-psutil
      - python3-dnf
      - python3-dev
      - build-essential
      - zlib1g-dev
      - libssl-dev
      - libbz2-dev
      - libncurses5-dev
      - libffi-dev
      - libreadline-dev
      - libsqlite3-dev
      - liblzma-dev
- name: Install Pyenv
  shell: curl https://pyenv.run | bash
  become_user: gdarruda
- name: Setting pyenv on zsh
  shell: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    echo 'eval "$(pyenv init -)"' >> ~/.zshrc
  become_user: gdarruda
- name: Install pyenv virtual plugin
  shell: git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
- name: Install drivers
  shell: ubuntu-drivers autoinstall
- name: Reboot machine
  ansible.builtin.reboot: